### ISSUE TITLE
Firefox support?

### ISSUE THREAD

**Issue by aeischeid** [tuvistavie/atomic-chrome-atom#11]
I have no idea if this is possible. Firefox has been implementing WebExtensions APIs so maybe the chrome side would be easy?

**Comment by danhper** [comment]
Hi, sorry for the late reply!
I will close here as this is an issue on the browser plugin side.
I saw you already reacted in https://github.com/tuvistavie/atomic-chrome/issues/5, so let's continue the discussion there
