### ISSUE TITLE
Cannot activate

### ISSUE THREAD

**Issue by WuTianming** [tuvistavie/atomic-chrome-atom#13]
Nothing happened after clicking on the button.

Chromium 53.0.2785.116 (Developer Build) (64-bit), Linux

Atom package installed with no error.

Help please!

**Comment by WuTianming** [comment]
Sorry -- it was caused by a delay. A minute later, it works.

**Comment by danhper** [comment]
@WuTianming No problem, glad it worked for you :smile:
