### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by jfairley** [tuvistavie/atomic-chrome-atom#17]
Pardon my ignorance here... I recognize that is a really neat bit of functionality, but I'm struggling to see a use case.

As I'm always looking for neat utilities to make life easier, can you help me see how this could be used day-to-day? The only thing I can come up with is controlling a remote box -- an Arduino, maybe...

**Comment by danhper** [comment]
Hi, there has already been a similar question [here](https://github.com/tuvistavie/atomic-chrome/issues/22), feel free to take a look :smile:
