### ISSUE TITLE
[REQUEST] Default to markdown instead of plain text

### ISSUE THREAD

**Issue by JustinAiken** [tuvistavie/atomic-chrome-atom#2]
..especially GFM for github

**Comment by danhper** [comment]
Totally agree. I am going to default to `.md`,
and if someone wants to change this I could eventually add a setting.
Thanks for the feedback.

**Comment by s-thom** [comment]
Why not have different 'languages' for different websites? `.md` for GitHub and Reddit, `.html` for GMail, other formatting for other things, etc.

**Comment by danhper** [comment]
@SecretOnline Thank you for the idea. I am planning to support this feature.
I think I will be able to finish it this week. I plan to allow to modify the list of sites from Chrome options.

See also
https://github.com/tuvistavie/atomic-chrome/issues/10

**Comment by danhper** [comment]
@JustinAiken Sorry for the delay, this should be fixed as of 0.3.0.
@SecretOnline The Atom plugin only receives the extension from the WS message,
so the customization part will be done in [tuvistavie/atomic-chrome](https://github.com/tuvistavie/atomic-chrome).

**Comment by JustinAiken** [comment]
> @JustinAiken Sorry for the delay, this should be fixed as of 0.3.0.

No worries, that was a very small delay to fix a huge void left in my life ever since I switched away from Sublime and couldn't use GhostText anymore! :)

**Comment by danhper** [comment]
Glad it can help! :smile:

**Comment by sirianni** [comment]
Great suggestion!

Has the option been implemented in the atomic-chrome extension?  I don't see any options exposed for the extension anywhere, and there are no commits associated with tuvistavie/atomic-chrome#10
